server:
  port: 9090
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/laplace
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

images:
  directory: C:/projects/Files/uploaded/
serverIp: localhost

#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB